version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    volumes:
      - ./src/frontend:/app:delegated
      - /app/node_modules
    command: sh -c "npm install --no-audit --no-fund && npm run dev -- -H 0.0.0.0 -p 3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./src/backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - PORT=3001
    volumes:
      - ./src/backend:/app:delegated
      - /app/node_modules
    command: sh -c "npm install --no-audit --no-fund && npm run start:dev"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
