version: '3.8'

services:
  frontend:
    volumes:
      - ./src/frontend:/app:delegated
      - /app/node_modules
    command: sh -c "npm install --no-audit --no-fund && npm run dev -- -p 3000 -H 0.0.0.0"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    volumes:
      - ./src/backend:/app:delegated
      - /app/node_modules
    command: sh -c "npm install --no-audit --no-fund && npm run start:dev"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres

# postgres использует настройки из docker-compose.yml (volume postgres_data сохраняет БД)
