[services]
  [services.backend]
    rootDir = "./src/backend"
    [services.backend.build]
      builder = "DOCKERFILE"
      dockerfilePath = "./Dockerfile"
    [services.backend.deploy]
      numReplicas = 1
      startCommand = "node dist/main.js"
    [services.backend.env]
      PORT = "3001"
      DATABASE_URL = "${postgres.DATABASE_URL}"

  [services.frontend]
    rootDir = "./src"
    [services.frontend.build]
      builder = "DOCKERFILE"
      dockerfilePath = "./Dockerfile"
    [services.frontend.deploy]
      numReplicas = 1
      startCommand = "npm start"
    [services.frontend.env]
      PORT = "3000"
      NEXT_PUBLIC_API_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"

[plugins]
  [plugins.postgres]
    enabled = true